# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [4]:
import numpy as np
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
'''
zero 是全0,empty是隨時要更改可以更改
'''

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


'\nzero 是全0,empty是隨時要更改可以更改\n'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [6]:
# 記得先 Import 正確的套件
np.array([1,2,3])

array([1, 2, 3])

In [28]:
# 參考解答

a = np.random.rand(2, 3)
b = np.array(a,dtype=int)
print(b)

[[0 0 0]
 [0 0 0]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [35]:
m = 20
n = 40
print(np.empty((2, 3), m-n))

TypeError: Cannot interpret '-20' as a data type