# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [21]:
'''
list會根據列，列出矩陣
tolist不將所有值都包在同一個矩陣
'''

'\nlist會根據列，列出矩陣\ntolist不將所有值都包在同一個矩陣\n'

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [38]:
# 記得先 Import 正確的套件
import numpy as np
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
'''
開始!
'''

'\n開始!\n'

In [59]:
a = np.random.randint(10, size=6) 
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

'''a是一維'''

[7 8 7 8 2 8]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


'a是一維'

In [61]:
b = np.random.randint(10, size=(3,4)) 
print(b)

print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

'''
b是二維
'''

[[3 3 8 0]
 [3 2 3 9]
 [6 4 8 4]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


'\nb是二維\n'

In [62]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

'''
c是三維
'''

[[[2 0]
  [8 4]
  [5 1]]

 [[1 9]
  [7 3]
  [8 5]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


'\nc是三維\n'

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [64]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 9, 4, 4, 7, 1]
[7, 9, 4, 4, 7, 1]


In [65]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[7, 9, 7, 9], [7, 7, 0, 0], [1, 9, 0, 5]]
[array([7, 9, 7, 9]), array([7, 7, 0, 0]), array([1, 9, 0, 5])]


In [66]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[5, 3], [3, 1], [7, 8]], [[9, 4], [5, 6], [8, 1]]]
[array([[5, 3],
       [3, 1],
       [7, 8]]), array([[9, 4],
       [5, 6],
       [8, 1]])]


In [76]:
def tolist(iterable):
    print(iterable)
    print([list(f) for f in list(iterable)])
print(tolist(a))
print(tolist(b))
print(tolist(c))

[7 9 4 4 7 1]


TypeError: 'numpy.int32' object is not iterable