# 範例
***

# [教學目標]

* 認識 NumPy 中提供的資料型態
* 了解各種型態的差異與定義
* 正確的比較型態判斷



In [30]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from 'C:\\Users\\SheHome\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
1.19.2


In [31]:
# 從一個陣列開始

a = np.arange(15).reshape(3, 5)
print(a) # 利用 print(...) 印出陣列
a # 利用 Jupyter 印出陣列

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
# 陣列的常用屬性
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
print(a.dtype) # int64
print(a.itemsize) # 8


type(a):  <class 'numpy.ndarray'>
a.dtype:  int32
int32
4


In [36]:
# numpy 中的型態判斷

print(a.dtype == 'int32') 
print(a.dtype)
print(a.dtype is 'int32') 
print(a.dtype is np.int32) 


True
int32
False
False


<>:5: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:5: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-36-cfd9eccc3322>:5: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print(a.dtype is 'int32')


In [34]:
# 資料型態的正確用法

print(a.dtype == 'int32') # True
print(a.dtype == np.int32) # True
print(a.dtype is np.dtype('int32')) # True


True
True
True
